export interface TaskContextInterface {
    openModal: boolean;
    listTask: TaskItemInterface[];
    isLoading: boolean;
}


// Generated by https://quicktype.io

export interface GetTaskRequestInterface {
    ok:   boolean;
    data: TaskItemInterface[];
}

export interface TaskItemInterface {
    id:             number;
    title:          string;
    description:    string;
    author:         string;
    republic_state: string;
    likes:          number;
    created_at:     string;
    updated_at:     string;
    deleted_at:     null;
}
